name: Using Terraform to automate Flask App Deployment to an EC2 Instance

on: push
    # branches: [ 'feature/**' ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.10
      
      - name: Create and activate virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  lint:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

  #     - name: Install linter
  #       run: pip install flake8

  #     - name: Run linter
  #       run: flake8 .