name: Deploy Random Quote of Day App to AWS EC2 Instance

on:
  pull_request:
    branches: main
  workflow_run:
    workflows: ["Build, Test and Lint Flask Application in branches other than main"]
    types: [ completed ]
    branches: [ main ]

env:
  # Credentials for AWS deployment 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: ./src/terraform    

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

