name: Deploy Random Quote of Day App to AWS EC2 Instance

on:
  pull_request:
    branches: main
  workflow_run:
    workflows: ["Build, Test and Lint Flask Application in branches other than main"]
    types: [ completed ]
    branches: [ main ]

env:
  # Credentials for AWS deployment 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        run: terraform apply -auto-approve -input=false

