name: Deploy Random Quote of Day App to AWS EC2 Instance

on:
  pull_request:
    branches: main
  workflow_run:
    workflows: ["Build, Test and Lint Flask Application in branches other than main"]
    types: [ completed ]
    branches: [ main ]

jobs:
  print:
    name: Example
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Echo hello world
        run:  echo "Hello World, from Mary Jonah"
